auction/urls.py
from django.urls import path

from .views import SearchAuctionsListView, AuctionBidForm, AuctionSell, \
    AuctionHistory, AuctionSellList, UserReviewCreate, UserReviewList, AuctionChat, AuctionChatList, AuctionApprove, \
    UserReviewUpdate

urlpatterns = [
    path('search/', SearchAuctionsListView.as_view(), name='auction-list'),
    path('room/<int:pk>', AuctionBidForm.as_view(), name='auction-detail'),
    path('sell/', AuctionSell.as_view(), name='sell'),
    path('sell/pending', AuctionSellList.as_view(), name='sell-pending'),
    path('history/', AuctionHistory.as_view(), name='history'),
    path('reviews/<int:pk>', UserReviewList.as_view(), name='reviews'),
    path('reviews/create/<int:pk>', UserReviewCreate.as_view(), name='review-create'),
    path('reviews/update/<int:pk>', UserReviewUpdate.as_view(), name='review-update'),
    path('chat/<int:pk>', AuctionChat.as_view(), name='auction-chat'),
    path('chatlist', AuctionChatList.as_view(), name='auction-chat-list'),
    path('approve/<int:pk>', AuctionApprove.as_view(), name='auction-approve'),
]

name_your_price/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('account/', include('accounts.urls')),
    path('purchase/', include('purchase.urls')),
    path('auction/', include('auction.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auction/models.py
import json

from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.db.models import Avg, Max
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django_celery_beat.models import PeriodicTask, IntervalSchedule, ClockedSchedule


class AuctionProduct(models.Model):
    class AuctionCategory(models.TextChoices):
        CARS = 'CA', _('Cars'),
        CLOCKS = 'CL', _('Clocks'),
        JEWELS = 'JE', _('Jewels'),
        TECHNOLOGY = 'TE', _('Technology'),
        NONE = 'NO', _('None'),

    name = models.CharField(max_length=128)
    date_start = models.DateTimeField(null=False)
    date_end = models.DateTimeField(null=False)
    description = models.TextField()
    product_image = models.ImageField(upload_to='images/')
    pending = models.BooleanField(default=True)
    seller = models.ForeignKey('Bidder', on_delete=models.PROTECT, related_name='auctioned_items')
    last_bidder = models.ForeignKey('Bidder', on_delete=models.PROTECT, null=True, default=None, unique=False)
    auto_bidders = models.ManyToManyField('Bidder', related_name='auto_auctions', default=None)
    category = models.CharField(
        max_length=2,
        choices=AuctionCategory.choices,
        default=AuctionCategory.NONE
    )

    @property
    def has_started(self):
        return self.date_start <= timezone.now() <= self.date_end

    @property
    def expired(self):
        return self.date_end <= timezone.now()

    @property
    def total(self):
        exist = self.auction_bids.exists()
        if exist:
            return self.auction_bids.aggregate(Max('amount')).get('amount__max')
        return 0

    @property
    def can_start(self):
        return not self.expired and not self.has_started

    def __str__(self):

        status = []
        if self.expired:
            status.append('Expired')
        if self.pending:
            status.append('Pending')
        if self.has_started:
            status.append('Started')

        joined = f"({', '.join(status)})" if status else ''
        return f'{self.name} {joined}'


class Bidder(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT, related_name='bidder')

    @property
    def last_bid(self):
        return Bid.objects.filter(user_bid=self).latest('date')

    def get_last_bid(self, auction: AuctionProduct):
        return auction.last_bidder.bids.filter(user_bid=self).aggregate(Max('amount'))

    @property
    def has_offered(self):
        return Bid().has_user_bid(self)

    @property
    def is_seller(self):
        return AuctionProduct.objects.filter(seller__user=self.user).count() > 0

    @property
    def has_ratings(self):
        return AuctionProduct.objects.filter(seller__user=self.user, ratings__isnull=False).count() > 0

    @property
    def average_ratings(self):
        return Rating.objects.filter(auction__seller_id=self).aggregate(Avg('vote'))

    @property
    def balance(self):
        if self.pk:
            auctions = [auction for auction in AuctionProduct.objects.filter(auction_bids__user_bid=self).distinct()]
            spent_coins = sum(Bid.objects.filter(auction=auction, user_bid=self).latest('date').amount
                              for auction in auctions)
            try:
                return self.user.purchase.coins - spent_coins
            except ObjectDoesNotExist:
                return 0
        return 0

    def __str__(self):
        return str(self.user)


class Bid(models.Model):
    amount = models.IntegerField()
    date = models.DateTimeField(auto_now=True)
    user_bid = models.ForeignKey(Bidder, models.PROTECT, related_name='bids')
    auction = models.ForeignKey(AuctionProduct, models.PROTECT, related_name='auction_bids')
    step = models.IntegerField(null=True, default=0)
    auto = models.BooleanField(default=False)
    max_offer = models.IntegerField(null=True, default=0)
    finished = models.BooleanField(default=False)

    def has_user_bid(self, user):
        return Bid.objects.filter(user_bid=user, auction=self.auction)

    def __str__(self):
        return f'{self.user_bid} at {self.auction} on {self.date} ({self.amount})'

    class Meta:
        ordering = ('-date',)


class Rating(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    auction = models.OneToOneField(AuctionProduct, on_delete=models.PROTECT, related_name='rating', default=None)
    bidder_rating = models.ForeignKey(Bidder, on_delete=models.PROTECT, related_name='bidder_ratings')
    vote = models.IntegerField()

    def __str__(self):
        return f'{self.bidder_rating} voted {self.auction}'


class Message(models.Model):
    chat = models.ForeignKey(AuctionProduct, on_delete=models.PROTECT, related_name='messages', default=None)
    text = models.CharField(max_length=265)
    sender = models.ForeignKey(Bidder, unique=False, on_delete=models.PROTECT, related_name='sent_messages')
    receiver = models.ForeignKey(Bidder, unique=False, on_delete=models.PROTECT, related_name='received_messages')
    date = models.DateTimeField(default=timezone.datetime.now)

    def __str__(self):
        return self.text


@receiver(post_save, sender=User)
def add_bidder(sender, instance, created, **kwargs):
    if created:
        Bidder.objects.create(user=instance)


@receiver(post_save, sender=Bid)
def place_auto_bid(sender, instance: Bid, created, **kwargs):
    if instance.auto:
        instance.auction.auto_bidders.add(instance.user_bid)
        instance.auction.save()

    auction = instance.auction
    if auction.last_bidder != instance.user_bid:
        auction.last_bidder = instance.user_bid
        auction.save()


@receiver(post_delete, sender=Bid)
def place_auto_bid(sender, instance: Bid, **kwargs):
    auction = instance.auction
    if auction.last_bidder == instance.user_bid:
        auction.last_bidder = None
        auction.save()
    if instance.user_bid in auction.auto_bidders.all():
        auction.auto_bidders.remove(instance.user_bid)
        auction.save()


@receiver(post_save, sender=Bid)
def subscribe_auto_bidder(sender, instance: Bid, **kwargs):
    if not instance.auto:
        return
    auction = instance.auction
    if instance.user_bid in auction.auto_bidders.all():
        auction.auto_bidders.add(instance.user_bid)
        auction.save()


@receiver(post_save, sender=AuctionProduct)
def add_periodic_task(sender, instance: AuctionProduct, **kwargs):
    if not instance.expired and not instance.pending:
        task_name = f'auction-{instance.id}-task'
        task_query = PeriodicTask.objects.filter(name=task_name)
        if task_query.exists():
            return
        schedule, _ = IntervalSchedule.objects.get_or_create(every=10, period=IntervalSchedule.SECONDS)
        periodic_task, _ = PeriodicTask.objects.get_or_create(interval=schedule, name=task_name,
                                                              task='auction.tasks.auto_bid',
                                                              args=json.dumps([instance.id]),
                                                              expires=instance.date_end)

        run_time = ClockedSchedule.objects.create(clocked_time=instance.date_end)
        PeriodicTask.objects.get_or_create(clocked=run_time, name=f'auction-{instance.id}-cancel-task',
                                           start_time=instance.date_start,
                                           task='auction.tasks.stop_auto_bid_task', args=json.dumps([periodic_task.id]),
                                           one_off=True)


@receiver(post_delete, sender=AuctionProduct)
def remove_tasks(sender, instance: AuctionProduct, **kwargs):
    task = PeriodicTask.objects.filter(name=f'{instance}-{instance.id}-task')
    if task.exists():
        task.get().delete()
        PeriodicTask.objects.get(name=f'{instance}-{instance.id}-cancel-task').delete()

auction/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils import timezone
from django.utils.text import gettext_lazy as _

from .models import Bid, AuctionProduct, Rating, Message


class BiddingForm(forms.ModelForm):
    amount = forms.IntegerField(min_value=1, required=True)
    auto_bid = forms.BooleanField(initial=True, required=False)
    auto_bid_amount = forms.IntegerField(required=False)
    step = forms.IntegerField(initial=1, min_value=1, required=False)

    def clean(self):
        cleaned_data = super(BiddingForm, self).clean()
        auto_bid = cleaned_data.get('auto_bid')
        auto_bid_amount = cleaned_data.get('auto_bid_amount')
        amount = cleaned_data.get('amount')
        step = cleaned_data.get('step')
        if not step:
            step = 1

        if auto_bid and not auto_bid_amount:
            raise ValidationError('Cannot send an auto bid amount without a max bid')
        if not auto_bid and auto_bid_amount:
            raise ValidationError('Cannot send a bid with a max amount without auto bid enabled')
        if auto_bid and amount + step > auto_bid_amount:
            raise ValidationError('Cannot send a bid with a max bid lower than the bid amount')

        return cleaned_data

    class Meta:
        model = Bid
        fields = ('amount',)


class SearchBiddingForm(forms.ModelForm):
    name = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Search'}),
        label='',
        initial='',
        required=False
    )
    sold = forms.BooleanField(required=False, initial=False)
    all_categories = forms.BooleanField(initial=True, required=False)
    category = forms.TypedChoiceField(required=False, choices=AuctionProduct.AuctionCategory.choices)
    price = forms.IntegerField(required=False, initial=0, label='Price grater than', min_value=0)
    advanced = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

    class Meta:
        model = AuctionProduct
        fields = ('name', 'category', 'sold', 'price')


class CreateAuctionProductForm(forms.ModelForm):
    date_start = forms.DateTimeField(
        input_formats=['%Y-%m-%dT%H:%M'],
        widget=forms.DateTimeInput(
            attrs={
                'type': 'datetime-local',
                'value': (timezone.now() + timezone.timedelta(days=1)).strftime('%Y-%m-%d %H:%M')},
            format='%Y-%m-%dT%H:%M')
    )
    date_end = forms.DateTimeField(
        input_formats=['%Y-%m-%dT%H:%M'],
        widget=forms.DateTimeInput(
            attrs={
                'type': 'datetime-local',
                'value': (timezone.now() + timezone.timedelta(days=2)).strftime('%Y-%m-%d %H:%M')},
            format='%Y-%m-%dT%H:%M')
    )

    def clean(self):
        cleaned_data = super(CreateAuctionProductForm, self).clean()
        start = cleaned_data.get('date_start')
        end = cleaned_data.get('date_end')
        if end < start:
            raise ValidationError('Date start cannot be grater than the start end')
        return cleaned_data

    class Meta:
        model = AuctionProduct
        fields = ('name', 'category', 'description', 'date_start', 'date_end', 'product_image')


class AuctionOrderingForm(forms.ModelForm):
    CHOICES = (
        ('name', _('Name')),
        ('category', _('Category')),
        ('last_bidder', _('Last bidder')),
        ('expired', _('Expired')),
        ('pending', _('Pending')),
    )

    ordering = forms.TypedChoiceField(required=False, choices=CHOICES, empty_value='name')
    is_seller = forms.BooleanField(required=False, initial=False)
    descending = forms.BooleanField(initial=False, required=False)

    class Meta:
        model = AuctionProduct
        fields = ('ordering',)


class ReviewCreationForm(forms.ModelForm):
    vote = forms.IntegerField(min_value=0, max_value=5)

    class Meta:
        model = Rating
        fields = ('title', 'description', 'vote')


class ChatMessage(forms.ModelForm):
    text = forms.Textarea()

    class Meta:
        model = Message
        fields = ('text',)


class SearchForm(forms.ModelForm):
    name = forms.CharField(required=False, widget=forms.TextInput(attrs={'placeholder': 'Search'}))

    class Meta:
        model = AuctionProduct
        fields = ('name',)

templates/auction/auction_approve.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %} Chat {% endblock %}

{% block content %}
    <div class="container">
        {% include 'navbar.html' %}
        {% include 'alert_message.html' %}
        {% if not object.pending %}
            <h1> This auction is already approved!</h1>
        {% else %}
            <h1> Approve this auction!</h1>
            <h2> Seller: {{ object.seller }}</h2>
            <h3> Current item: <strong> {{ object.name }} </strong> </h3>
            <p> Start: <strong class=""> {{ object.date_start | date:"M d, Y h:m:s" }} </strong> </p>
            <p> End: <strong class="auction-end">{{ object.date_end | date:"M d, Y h:m:s" }} </strong></p>
            <p> Category: <strong class="auction-end">{{ object.get_category_display }} </strong></p>
            <p> Description: <strong class="auction-end">{{ object.description }} </strong></p>

            <img class="auction-image" src="{{ object.product_image.url }}" alt="Auction image">
            {% if object.expired %}
                <h4 class="pt-3"> This auction has ended, so it can't be approved!</h4>
            {% else %}
                <form method="post" class="my-3">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <button id="send-bid" type="submit" class="btn btn-primary
                        {% if object.has_started %} disabled {% endif %}
                        "> Approve </button>
                </form>
            {% endif %}
        {% endif %}
    </div>
{% endblock %}

templates/auction/auction_chat.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_filters %}

{% block title %} Chat {% endblock %}

{% block content %}
    <div class="container">
        {% include 'navbar.html' %}
        {% include 'alert_message.html' %}
        <h1> Chat for auction {{ object.name }} </h1>
        {% with object.messages.all as messages  %}
            <div class="chat-box">
                {% if messages %}
                    <div class="chat-container">
                        <ul id="chat-message-list" class="list-group my-3">
                            {% for message in object.messages.all %}
                                <li class="list-group-item">{{ message.sender }}: {{ message }} </li>
                            {% endfor %}
                        </ul>
                    </div>
                {% else %}
                    <h4 id="no-message-error"> No messages found</h4>
                    <div class="chat-container">
                        <ul id="chat-message-list" class="list-group my-3"></ul>
                    </div>
                {% endif %}
            </div>
            <form method="post">
                {% csrf_token %}
                {{ form | crispy }}
                <button id="send-message" type="submit" class="btn btn-primary"> Send message </button>
            </form>
        {% endwith %}


    </div>
        <script>
            const chatRoom = {% if object %} {{ object.pk }} {% else %} null {% endif %};
            const userId = '{{ user.id }}'
        </script>
{% endblock %}
{% block script %}
     <script src="{% static 'script/chat.js' %}"></script>
{% endblock %}

templates/auction/auction_chat_listview.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %} Chat {% endblock %}

{% block content %}
    <div class="container">
        {% include 'navbar.html' %}
        {% include 'alert_message.html' %}
        <form>
            {{ form | crispy }}
            <input type="submit" class="btn btn-primary" value="Submit">
        </form>
        {% if not object_list %}
            <h1>Nobody sent a message</h1>
        {% else %}
            <h1>Your chats:</h1>
            <div>
                {% for chat in object_list %}
                    <div class="card mb-3">
                        <div class="card-body">
                            <div class="chat">
                                <a href="{% url 'auction-detail' chat.pk %}" class="text-decoration-none">
                                    <img src="{{  chat.product_image.url }}" alt="mdo" width="32" height="32" class="rounded-circle">
                                </a>
                                <h5 class="card-title mb-2 text-muted d-inline"> {{ chat }}</h5>

                            </div>
                            <p class="card-text"> {{ chat.description }}</p>
                            <a href="{% url 'auction-chat' chat.id %}" class="card-link"> Go to chat </a>
                            {% if chat.pending and not chat.has_started and not chat.expired %}
                                <a href="{% url 'auction-approve' chat.id %}" class="card-link"> Approve </a>
                            {% endif %}
{#                            <h5 class="card-title">{{ rating.title }}</h5>#}
{#                            <h6 class="card-subtitle mb-2 text-muted d-inline"> vote: {{ rating.vote }} / 5</h6>#}
                            <p class="card-text"> {{ rating.description }}</p>
{#                            <a href="{% url 'auction-detail' rating.auction.pk %}" class="card-link"> {{ rating.auction }}</a>#}
{#                            {% if rating.bidder_rating == user.bidder %}#}
{#                                <a href=" {% url 'review-update' rating.pk %}" class="card-link"> Edit </a>#}
{#                            {% endif %}#}
                        </div>
                    </div>
{#                    <li class="list-group-item">{{ chat }}#}
{#                        <a href="{% url 'auction-chat' chat.id %}"> Go to chat </a>#}
{#                        {% if chat.pending %}#}
{#                            <a href="{% url 'auction-approve' chat.id %}"> Approve </a>#}
{#                        {% endif %}#}
{#                    </li>#}
                {% endfor %}
            </div>
        {% endif %}
    </div>
{% endblock %}

{% block footer %}
    {% include 'pagination.html' %}
{% endblock %}

templates/auction/auction_detail.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}
{% load auction_search_filters %}

{% block title %} Auction room {% endblock %}

{% block content %}
    <div class="container">
        {% include 'navbar.html' %}
        {% include 'alert_message.html' %}
        {% if object.pending %}
            <h1> This auction needs to be approved first!</h1>
        {% elif object.expired %}
            <h1> This auction has ended!</h1>
        {% else %}
            <h1> Welcome to this bidding room!</h1>
        {% endif %}
            <h2> Seller: <a href="{% url 'reviews' object.seller.id %}">{{ object.seller }} </a></h2>
            {% if not user.bidder %}
                <h2> First time? Start now!</h2>
            {% else %}
                <h2> You now have <span class="total-coins">{{ user.bidder.balance }} </span> coins!</h2>
                {% has_offered user.bidder object as offered %}
                {% if offered %}
                    {% auction_last_offer user.bidder object as user_last_offer %}
                    <h2> Last offer was of <span class="last-bid">  {{ user_last_offer.amount }} </span></h2>
                {% endif %}
            {% endif %}
            <h3> Current item: <strong> {{ object.name }} </strong></h3>
            <h3> Total: <strong class="total-amount"> {{ object.total }} </strong></h3>
            <img class="auction-image" src="{{ object.product_image.url }}" alt="Auction image">
            {% with object.last_bidder as last_bidder %}
                {% if last_bidder %}
                    <p> Last bidder: <strong class="last-bidder"> {{ object.last_bidder }}</strong></p>
                {% else %}
                    <p> Nobody bid yet!</p>
                {% endif %}
            {% endwith %}
            <p class="auction-end visually-hidden"> {{ object.date_end | date:"M d, Y h:m:s" }} </p>
            <p> Remaining time <strong class="count-down-time"> n/a </strong></p>
            <p> Description: {{ object.description }}</p>
            <form method="post">
                {% csrf_token %}
                {{ form | crispy }}
                <button id="send-bid" type="submit" class="btn btn-primary"> Send bid</button>
            </form>
            <ul id="bidders-list" class="list-group my-3 bids-container">
                {% for bid in object.auction_bids.all %}
                    <li class="list-group-item">
                        {% if bid.user_bid.user_id == user.id %}
                            You
                        {% else %}
                            {{ bid.user_bid }}
                        {% endif %}
                        bid {{ bid.amount }} </li>
                {% endfor %}
            </ul>
    </div>
    <script>
        const room = {{ object.pk }} ;
        const currentUser = '{{ user }}';
    </script>
{% endblock %}
{% block script %}

{% endblock %}

templates/auction/auction_history.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}
{% load auction_search_filters %}

{% block title %} History {% endblock %}

{% block content %}
    <div class="container">
        {% include 'navbar.html' %}
        {% include 'alert_message.html' %}
        <form>
            {{ form | latest_search:last_search | crispy }}
            <input type="submit" class="btn btn-primary" value="Submit">
        </form>
        <h1> Your auctions </h1>
        {% if object_list %}
            <table class="table">
                <thead>
                <tr>
                    <th scope="col"> Name </th>
                    <th scope="col"> Category </th>
                    <th scope="col"> Last bidder </th>
                    <th scope="col"> Won </th>
                    <th scope="col"> Status </th>
                    <th scope="col"> Feedback</th>
                    <th scope="col"> Pending</th>
                    <th scope="col"> Chat</th>
                    <th scope="col"> Owned </th>
                </tr>
                </thead>
                <tbody>
                {% for auction in object_list %}
                    <tr>
                        {% if auction.has_started and not auction.pending and not auction.expired %}
                            <td scope="row"> <a href="{% url 'auction-detail' auction.pk %}"> {{ auction }} </a>  </td>
                        {% else %}
                            <td scope="row"> {{ auction }} </td>
                        {% endif %}
                        <td> {{ auction.get_category_display }} </td>
                        <td> {% if not auction.last_bidder %} Nobody bid {% else %} {{ auction.last_bidder }} {% endif %} </td>
                        <td> {% if auction.last_bidder == user.bidder and auction.expired %} Yes {% else %} No {% endif %}</td>
                        <td>
                            {% if auction.expired %}
                                End
                            {% elif auction.has_started %}
                                {% if auction.pending %}
                                    Cannot start
                                {% else %}
                                    In progress
                                {% endif %}
                            {% else %}
                                Will begin
                            {% endif %}</td>
                        <td> {% if auction.last_bidder == user.bidder and auction.expired %}
                            {% if auction.rating %}
                                <a href="{% url 'reviews' auction.seller.pk %}">See feedbacks</a>
                            {% else %}
                                <a href="{% url 'review-create' auction.pk %}">Send feedback</a>
                            {% endif %}</td>
                        {% endif %}
                        <td>
                            {% if auction.pending %}
                                {% if auction.expired %}
                                    <span>No</span>
                                {% elif auction.has_started %}
                                    <span>Yes</span>
                                {% else %}
                                    <a href="{% url 'auction-chat' auction.id %}"> Yes (chat) </a>
                                {% endif %}
                            {% else %}
                                <span>No</span>
                            {% endif %}
                        </td>
                        <td>
                            {% if auction.seller.user == user %}
                                <a href="{% url 'auction-chat' auction.id %}"> Chat </a>
                            {% endif %}
                        </td>
                        <td>
                            {% if auction.seller.user == user %}
                                 Yes
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>

            </table>
        {% else %}
            <h2> You have nothing to show </h2>
        {% endif %}
    </div>
{% endblock %}

{% block footer %}
    {% include 'pagination.html' %}
{% endblock %}

templates/auction/auction_list.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}
{% load auction_search_filters %}

{% block title %} Auctions {% endblock %}

{% block content %}
    <div class="container">
        {% include 'navbar.html' %}
        <form class="my-2">
            {% if last_search %}
                {{ form | latest_search:last_search | crispy }}
            {% else %}
                {{ form | crispy }}
            {% endif %}
            <input type="submit" class="btn btn-primary" value="Submit">
            <a class="btn btn-primary" href="{% url 'auction-list' %}"> Reset </a>
        </form>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-5">
            {% for auction in object_list %}
                {% include 'auction_preview.html' %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

{% block footer %}
    {% include 'pagination.html' %}
{% endblock %}

templates/auction/auction_pending.html
{% extends 'base.html' %}

{% block title %} Approve {% endblock %}

{% block content %}
    <div class="container">
        {% include 'navbar.html' %}
        <h1> Your pending requests</h1>
        <h5> Add a new one <a class="h5" href="{% url 'sell' %}"> here </a></h5>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-5">
            {% for auction in object_list %}
                {% include 'auction_pending_preview.html' %}
            {% endfor %}
        </div>

    </div>
{% endblock %}

{% block footer %}
    {% include 'pagination.html' %}
{% endblock %}

templates/auction/auction_sell.html
{% extends 'base.html' %}
{% load i18n %}

{% load crispy_forms_filters %}

{% block title %} Sell {% endblock %}

{% block content %}
    <div class="container">
        {% include 'navbar.html' %}
        <h1> Add a new product </h1>
        <h5> See product already submitted <a class="h5" href="{% url 'sell-pending' %}"> here </a> </h5>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form | crispy }}
        <button class="btn btn-primary"> {% trans 'Submit' %} </button>
        </form>

    </div>
{% endblock %}